# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Fabio Durastante
email: fabio.durastante@unipi.it
description: >- # this means to ignore newlines until "baseurl:"
  I'm a Researcher (RTDa) in Numerical Mathematics at Pisa University
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fdurastante.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Cirdans-Home
github_username:  Cirdans-Home

# SEO Settings
twitter:
  username: Cirdans-Home
  card: summary

social:
  name: Fabio Durastante
  links:
    - https://twitter.com/CirdansHome
    - https://www.linkedin.com/in/fdurastante/
    - https://github.com/Cirdans-Home
    - https://www.researchgate.net/profile/Fabio-Durastante
    - https://scholar.google.it/citations?user=sB3fLcMAAAAJ&hl=it
    - https://orcid.org/0000-0002-1412-8289

google-site-verification: google149f3f1f84e56dc5.html

# Settings of the template
username: Fabio Durastante
user_description: I'm a Researcher (RTDa) in Numerical Mathematics at Pisa University
user_title: Researcher

# Build settings
plugins:
  - jekyll-maps
  - jekyll-sitemap
  - jekyll-seo-tag

mapping:
 provider: openstreetmap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
